version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: emr
      POSTGRES_PASSWORD: example
      POSTGRES_DB: emrdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgdata:
  qdrant_data:
